<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP773pai\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP773pai/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP773pai.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP773pai\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP773pai\App_KernelDevDebugContainer([
    'container.build_hash' => 'P773pai',
    'container.build_id' => '756d3e4d',
    'container.build_time' => 1677806614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP773pai');
