<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRg4bESA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRg4bESA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRg4bESA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRg4bESA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRg4bESA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rg4bESA',
    'container.build_id' => '9b110932',
    'container.build_time' => 1678297598,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRg4bESA');
